fix build error on pb2 for Linux probably a conflict C vs C++, and mismatch with #include <inttypes.h> or #define __STDC_FORMAT_MACROS solved with std::string :->
connector-php-7.1.0/Zend/zend_long.h:60:28: error: expected ')' before 'PRId64'
 # define ZEND_LONG_FMT "%" PRId64
                            ^
/connector-php-7.1.0/ext/mysql_xdevapi/php_mysqlx.cc:75:30: note: in expansion of macro 'ZEND_LONG_FMT'
  snprintf(buf, sizeof(buf), (ZEND_LONG_FMT), MYSQL_XDEVAPI_G(net_read_timeout));
                              ^
/connector-php-7.1.0/ext/mysql_xdevapi/php_mysqlx.cc:75:80: error: expected ')' before ';' token
  snprintf(buf, sizeof(buf), (ZEND_LONG_FMT), MYSQL_XDEVAPI_G(net_read_timeout));